# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1ad67b16501ae9048013ab77665e8394897f114f2082a8a0f80f9bc379a165c51771f7e1889413c1cb8dde7236c8fa2bd3e001edc321767cafe1c2abdbc774a

test:
  secret_key_base: a946f342956b7d8f39bd750821cc35984ec8c2c80ee68fa5b5c8b776a2fb3ae481e3bd39337dab94b2aaf4eff51f2c2ddf603e2c560f41de961a8b022df02f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
